# Generated by Django 6.0.7 on 2026-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_location',
            field=models.CharField(blank=True, default='Central Plaza', max_length=100),
        ),
    ]
