# Generated by Django 6.1 on 2026-08-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_reset_otp_user_reset_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor / Tourist / Pilgrim'), ('site_manager', 'Site Manager / Tourism Authority'), ('emergency_service', 'Emergency Services / First Responder'), ('admin', 'Government / Event Admin'), ('security_officer', 'Security Officer')], default='visitor', max_length=30),
        ),
    ]
