# Generated by Django 6.1 on 2026-08-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('route_coordinates_json', models.TextField(blank=True, help_text='List of [lat, lng] waypoints for response route', null=True)),
                ('eta_minutes', models.IntegerField(default=5)),
                ('status', models.CharField(default='en_route', max_length=20)),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=120)),
                ('unit_type', models.CharField(choices=[('police', 'Police & Security Patrol'), ('medical_team', 'Medical First Responders'), ('fire_rescue', 'Fire & Rescue Service'), ('park_ranger', 'Park Rangers / Forest Eco Guard'), ('disaster_response', 'Disaster Relief Team')], default='police', max_length=30)),
                ('contact_phone', models.CharField(default='+1-800-SAFE-911', max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available on Patrol'), ('dispatched', 'Dispatched to Emergency'), ('on_scene', 'On Scene'), ('busy', 'Unavailable / Busy')], default='available', max_length=20)),
                ('current_lat', models.FloatField(default=20.5937)),
                ('current_lng', models.FloatField(default=78.9629)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencySOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sos_code', models.CharField(max_length=20, unique=True)),
                ('location_name', models.CharField(default='Pilgrimage Shrine Main Corridor', max_length=200)),
                ('latitude', models.FloatField(default=20.5937)),
                ('longitude', models.FloatField(default=78.9629)),
                ('sender_name', models.CharField(default='Anonymous Visitor', max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(choices=[('medical', 'Medical Emergency'), ('stampede', 'Stampede / Overcrowding Hazard'), ('fire', 'Fire / Smoke Hazard'), ('lost_person', 'Lost Person / Child'), ('landslide', 'Landslide / Environmental Barrier'), ('wildlife_hazard', 'Wildlife / Eco Encounter')], default='medical', max_length=30)),
                ('urgency', models.CharField(choices=[('low', 'Low Urgency'), ('medium', 'Medium Urgency'), ('high', 'High Urgency'), ('critical', 'Critical Life-Threatening')], default='high', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified Incident'), ('dispatched', 'Responder Dispatched'), ('resolved', 'Resolved & Safe'), ('false_alarm', 'False Alarm')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
