# Generated by Django 6.1 on 2026-08-16 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_dispatchrecord_emergencyresponseunit_emergencysos'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyresponseunit',
            name='assigned_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_units', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='alerts.emergencyresponseunit'),
        ),
        migrations.AddField(
            model_name='emergencysos',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencysos',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='dispatchrecord',
            name='sos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='alerts.emergencysos'),
        ),
    ]
