# Generated by Django 6.1 on 2026-08-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        ('detection', '0003_detection_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_hash', models.CharField(max_length=64)),
                ('detections_processed', models.IntegerField(default=0)),
                ('pii_purged', models.BooleanField(default=True)),
                ('anonymous_aggregation_verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SiteEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Central Pilgrim Plaza', max_length=150)),
                ('temperature_c', models.FloatField(default=28.5)),
                ('weather_condition', models.CharField(default='Clear', max_length=50)),
                ('humidity', models.IntegerField(default=60)),
                ('precipitation_risk', models.IntegerField(default=10)),
                ('shuttle_availability_pct', models.IntegerField(default=85)),
                ('parking_occupancy_pct', models.IntegerField(default=62)),
                ('traffic_congestion_level', models.CharField(default='Moderate', max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali')], default='en', max_length=10)),
                ('category', models.CharField(choices=[('safety_notice', 'Safety Notice'), ('pilgrimage_route', 'Pilgrimage Route Advice'), ('eco_trail_rules', 'Eco-Trail Rule'), ('emergency_info', 'Emergency Helpline')], default='safety_notice', max_length=30)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('site_type', models.CharField(choices=[('pilgrimage', 'Pilgrimage Shrine / Temple'), ('eco_tourism', 'Eco-Tourism Trail / Sanctuary'), ('transit', 'Transit / Concourse Hub'), ('event_gate', 'Event Plaza / Gate')], default='pilgrimage', max_length=30)),
                ('capacity_limit', models.IntegerField(default=500)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=15)),
                ('warning_threshold', models.IntegerField(default=350)),
                ('coordinates_json', models.TextField(blank=True, help_text='GeoJSON polygon or array of [lat, lng] points', null=True)),
                ('center_lat', models.FloatField(default=20.5937)),
                ('center_lng', models.FloatField(default=78.9629)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnusualIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('stampede_risk', 'Stampede & Surge Hazard'), ('rapid_dispersion', 'Panic / Rapid Dispersion'), ('bottleneck_congestion', 'Bottleneck Stagnation'), ('restricted_entry_breach', 'Geofence / Restricted Zone Breach'), ('medical_hazard', 'Thermal / Medical Hazard')], max_length=40)),
                ('risk_score', models.IntegerField(default=50)),
                ('details', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unusual_incidents', to='detection.detection')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unusual_incidents', to='analytics.zone')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField()),
                ('predicted_count', models.IntegerField()),
                ('predicted_risk', models.CharField(default='low', max_length=15)),
                ('confidence_score', models.FloatField(default=0.92)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='camera.camera')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='analytics.zone')),
            ],
            options={
                'ordering': ['forecast_time'],
            },
        ),
    ]
