# Generated by Django 6.1 on 2026-08-20 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(choices=[('entry_restriction', 'Gate / Entry Restriction'), ('sudden_surge', 'Sudden Crowd Increase'), ('route_blockage', 'Route Blockage'), ('emergency_incident', 'Emergency Incident'), ('visitor_diversion', 'Temporary Visitor Diversion')], default='entry_restriction', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('default_intensity', models.CharField(default='medium', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='connected_zones',
            field=models.ManyToManyField(blank=True, to='analytics.zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zone',
            name='emergency_route_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='entry_points',
            field=models.JSONField(blank=True, default=list, help_text='List of entry point names or coordinates'),
        ),
        migrations.AddField(
            model_name='zone',
            name='exit_points',
            field=models.JSONField(blank=True, default=list, help_text='List of exit point names or coordinates'),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='location_name',
            field=models.CharField(default='Bada Danda', max_length=150),
        ),
        migrations.AlterField(
            model_name='visitorguidance',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('or', 'Odia'), ('es', 'Spanish'), ('fr', 'French'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali')], default='en', max_length=10),
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('intensity', models.CharField(default='medium', max_length=20)),
                ('input_state_json', models.TextField(blank=True, null=True)),
                ('simulated_results_json', models.TextField(blank=True, null=True)),
                ('affected_zones_json', models.TextField(blank=True, null=True)),
                ('ripple_effect_json', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('primary_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='analytics.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
