# Generated by Django 6.0.7 on 2026-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_limit', models.IntegerField(default=50)),
                ('medium_limit', models.IntegerField(default=150)),
                ('high_limit', models.IntegerField(default=300)),
            ],
        ),
    ]
