# Generated by Django 6.0.7 on 2026-08-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_riskthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
