# Generated by Django 6.1 on 2026-08-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='latitude',
            field=models.FloatField(blank=True, default=20.5937, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='longitude',
            field=models.FloatField(blank=True, default=78.9629, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='analytics.zone'),
        ),
    ]
